package com.familylogbook.app.data.auth

import android.app.Activity
import android.content.Context
import android.content.Intent
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.android.gms.common.ConnectionResult
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider

/**
 * Helper class for Google Sign-In integration.
 * Handles the Google Sign-In flow and credential management.
 */
class GoogleSignInHelper(private val context: Context) {
    
    private val auth = FirebaseAuth.getInstance()
    
    /**
     * Creates a GoogleSignInClient configured for Firebase Authentication.
     */
    fun getSignInClient(): GoogleSignInClient {
        // Get default web client ID from google-services.json
        // Firebase automatically configures this
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getDefaultWebClientId())
            .requestEmail()
            .build()
        
        return GoogleSignIn.getClient(context, gso)
    }
    
    /**
     * Gets the default web client ID from google-services.json.
     * This is required for Firebase Authentication with Google Sign-In.
     * The Google Services plugin automatically generates this resource from google-services.json.
     * Falls back to parsing google-services.json directly if resource is not available.
     */
    private fun getDefaultWebClientId(): String {
        // First, try to get from resources (generated by Google Services plugin)
        return try {
            val resources = context.resources
            val clientIdResourceId = resources.getIdentifier(
                "default_web_client_id",
                "string",
                context.packageName
            )
            
            if (clientIdResourceId != 0) {
                val clientId = resources.getString(clientIdResourceId)
                android.util.Log.d("GoogleSignInHelper", "Got default_web_client_id from resources")
                return clientId
            } else {
                android.util.Log.w(
                    "GoogleSignInHelper",
                    "default_web_client_id resource not found, trying to parse google-services.json directly"
                )
                // Fallback: parse google-services.json directly
                parseWebClientIdFromJson()
            }
        } catch (e: Exception) {
            android.util.Log.e("GoogleSignInHelper", "Error getting default_web_client_id from resources", e)
            try {
                // Fallback: parse google-services.json directly
                parseWebClientIdFromJson()
            } catch (e2: Exception) {
                android.util.Log.e("GoogleSignInHelper", "Error parsing google-services.json", e2)
                // Last resort: use hardcoded client ID from google-services.json
                // This is the web client ID (client_type: 3) from your google-services.json
                android.util.Log.w("GoogleSignInHelper", "Using hardcoded fallback client ID")
                return "1068067776552-9mfqj2e984j7ehc151ucj6125o13vav4.apps.googleusercontent.com"
            }
        }
    }
    
    /**
     * Parses google-services.json to extract web client ID (client_type: 3).
     * This is a fallback if the Google Services plugin hasn't generated the resource yet.
     */
    private fun parseWebClientIdFromJson(): String {
        return try {
            val inputStream = context.assets.open("google-services.json")
                ?: throw IllegalStateException("google-services.json not found in assets")
            
            val jsonString = inputStream.bufferedReader().use { it.readText() }
            val jsonObject = org.json.JSONObject(jsonString)
            
            // Navigate to: client[0].oauth_client[] and find client_type: 3
            val clients = jsonObject.getJSONArray("client")
            if (clients.length() == 0) {
                throw IllegalStateException("No clients found in google-services.json")
            }
            
            val firstClient = clients.getJSONObject(0)
            val oauthClients = firstClient.getJSONArray("oauth_client")
            
            for (i in 0 until oauthClients.length()) {
                val oauthClient = oauthClients.getJSONObject(i)
                val clientType = oauthClient.optInt("client_type", -1)
                
                if (clientType == 3) {
                    // This is the web client ID
                    val clientId = oauthClient.getString("client_id")
                    android.util.Log.d("GoogleSignInHelper", "Parsed web client ID from google-services.json")
                    return clientId
                }
            }
            
            throw IllegalStateException("Web client ID (client_type: 3) not found in google-services.json")
        } catch (e: java.io.FileNotFoundException) {
            // google-services.json might not be in assets, try reading from file system
            try {
                val file = java.io.File(context.filesDir.parent, "google-services.json")
                if (!file.exists()) {
                    throw IllegalStateException("google-services.json not found. Make sure it's in app/ folder.")
                }
                
                val jsonString = file.readText()
                val jsonObject = org.json.JSONObject(jsonString)
                
                val clients = jsonObject.getJSONArray("client")
                val firstClient = clients.getJSONObject(0)
                val oauthClients = firstClient.getJSONArray("oauth_client")
                
                for (i in 0 until oauthClients.length()) {
                    val oauthClient = oauthClients.getJSONObject(i)
                    val clientType = oauthClient.optInt("client_type", -1)
                    
                    if (clientType == 3) {
                        val clientId = oauthClient.getString("client_id")
                        android.util.Log.d("GoogleSignInHelper", "Parsed web client ID from google-services.json file")
                        return clientId
                    }
                }
                
                throw IllegalStateException("Web client ID (client_type: 3) not found in google-services.json")
            } catch (e2: Exception) {
                throw IllegalStateException(
                    "Failed to parse google-services.json. " +
                    "Make sure it's in app/ folder and contains oauth_client with client_type: 3. " +
                    "Error: ${e2.message}"
                )
            }
        } catch (e: Exception) {
            throw IllegalStateException(
                "Failed to parse google-services.json. Error: ${e.message}"
            )
        }
    }
    
    /**
     * Creates an Intent to start the Google Sign-In flow.
     * Use this with ActivityResultLauncher.
     */
    fun getSignInIntent(): Intent {
        return getSignInClient().signInIntent
    }
    
    /**
     * Handles the result from Google Sign-In activity.
     * Returns the GoogleSignInAccount if successful, null otherwise.
     * Throws exception with detailed error message if sign-in fails.
     */
    fun handleSignInResult(data: Intent?): GoogleSignInAccount? {
        return try {
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            val account = task.getResult(ApiException::class.java)
            account
        } catch (e: ApiException) {
            // ApiException status codes
            // CommonStatusCodes constants: SIGN_IN_CANCELLED = 12501, SIGN_IN_FAILED = 12500, etc.
            // ConnectionResult codes: NETWORK_ERROR = 2, INTERNAL_ERROR = 8, INVALID_ACCOUNT = 5, SIGN_IN_REQUIRED = 4
            // DEVELOPER_ERROR = 10 (usually means SHA-1 mismatch or wrong client ID)
            val errorMessage = when (e.statusCode) {
                10 -> // DEVELOPER_ERROR - usually SHA-1 fingerprint mismatch or wrong client ID
                    "Greška konfiguracije. Provjeri da li je SHA-1 fingerprint dodan u Firebase Console i da li je google-services.json pravilno konfiguriran."
                ConnectionResult.NETWORK_ERROR -> 
                    "Greška mreže. Provjeri internetsku vezu."
                ConnectionResult.INTERNAL_ERROR -> 
                    "Interna greška. Pokušaj ponovo."
                ConnectionResult.INVALID_ACCOUNT -> 
                    "Nevažeći račun. Provjeri svoj Google račun."
                ConnectionResult.SIGN_IN_REQUIRED -> 
                    "Potrebna je prijava. Pokušaj ponovo."
                12501 -> // CommonStatusCodes.SIGN_IN_CANCELLED
                    "Google prijava je otkazana."
                12500 -> // CommonStatusCodes.SIGN_IN_FAILED
                    "Google prijava nije uspjela. Provjeri svoj Google račun."
                17 -> // CommonStatusCodes.API_NOT_CONNECTED
                    "Google servis nije povezan. Provjeri internetsku vezu."
                15 -> // CommonStatusCodes.TIMEOUT
                    "Google prijava je istekla. Pokušaj ponovo."
                else -> 
                    "Google prijava nije uspjela (${e.statusCode}). Pokušaj ponovo."
            }
            android.util.Log.e("GoogleSignInHelper", "Google sign-in failed: $errorMessage (code: ${e.statusCode})", e)
            throw Exception(errorMessage)
        } catch (e: Exception) {
            // Re-throw with user-friendly message
            throw e
        }
    }
    
    /**
     * Gets Firebase Auth credential from GoogleSignInAccount.
     */
    fun getFirebaseCredential(account: GoogleSignInAccount): com.google.firebase.auth.AuthCredential {
        val idToken = account.idToken
            ?: throw IllegalStateException("Google ID token is null")
        return GoogleAuthProvider.getCredential(idToken, null)
    }
}
